#!/bin/busybox sh

error() {
    echo ERROR! $1
    sleep 10
    # exec /bin/busybox sh

    echo 1 > /proc/sys/kernel/sysrq
    echo b > /proc/sysrq-trigger
}

format() {
sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' << EOF | fdisk /dev/sda
  d # delete
  1 # number 1
  d # delete
  2 # number 2
  d # delete
  3 # number 3
  d # delete
  4 # number 4
  d # delete
  5 # number 5
  n # new partition
  p # primary partition
  1 # partition number 1
    # default - start at beginning of disk
    # default, extend partition to end of disk
  w # write the partition table
  q # and we're done
EOF

# new fs (ext4 not available in busybox)
mkfs.ext2 /dev/sda1
# mount
mount /dev/sda1 /storage
}

/bin/busybox mkdir -p /sys /proc /run /tmp /sbin

/bin/busybox --install -s

mount -t devtmpfs none /dev
mkdir /dev/pts
mount -t devpts none /dev/pts
mount -t sysfs none /sys
mount -t proc none /proc

mkdir /storage/
for i in /dev/sd??
do
    mount $i /storage || continue
    sz=`df | grep "/storage$" | grep -o '[0-9]*' | head -n 2 | tail -n 1`
    [ $sz -gt 1000000 ] && break # (sz in KB) => ~1GB
    umount /storage
done
# try to format the disk
mount | grep /storage || format
# error
mount | grep /storage || error "Failed to mount /storage"
mkdir -p /storage/casper

SERVER=`cat /proc/cmdline | grep -o 'server=[^\ ]*' | grep -o '[^=]*$'`

BASEURL="http://${SERVER}/casper"
mkdir -p /storage/torrent
rm -rf /storage/torrent/*.torrent
IMAGE=`cat /proc/cmdline | grep -o 'imgname=[^\ ]*' | grep -o '[^=]*$'`

cat /proc/cmdline | grep forcedownload
FORCE_DOWNLOAD=$?

[ $FORCE_DOWNLOAD -eq 0 ] && rm -rf /storage/casper/*

cd /storage/torrent

for i in filesystem.squashfs kernel.img initrd.img
do
    wget ${BASEURL}/${IMAGE}/$i.torrent
done
clear

gettorrent *.torrent || error "Failed to download torrent"
sync

IP=`ip addr show dev eth0 | grep -o 'inet\ [^\ /]*' | cut -d\  -f2`
ROOM_NUMBER=`echo $IP | cut -d. -f3`
RIG_NUMBER=`echo $IP | cut -d. -f4`
HOSTNAME=`printf rig-%03d-%03d $ROOM_NUMBER $RIG_NUMBER`
TZ=Europe/Rome
cd /storage/casper
kexec kernel.img initrd.img "boot=casper hostname=${HOSTNAME} timezone=${TZ} imgname=${IMAGE} net.ifnames=0 amdgpu.ppfeaturemask=0xffffffff" || error "kexec failed!"
