#!/bin/busybox sh

error() {
    echo ERROR! $1
    exec /bin/busybox sh
}

/bin/busybox mkdir -p /sys /proc /run /tmp /sbin

/bin/busybox --install -s

mount -t devtmpfs none /dev
mkdir /dev/pts
mount -t devpts none /dev/pts
mount -t sysfs none /sys
mount -t proc none /proc

mkdir /storage/
for i in /dev/sd??
do
    mount $i /storage || continue
    sz=`df | grep "/storage$" | grep -o '[0-9]*' | head -n 2 | tail -n 1`
    [ $sz -gt 1000000 ] && break # (sz in KB) => ~1GB
    umount /storage
done
mount | grep /storage || error "Failed to mount /storage"
mkdir -p /storage/casper

BASEURL='http://10.8.0.1/casper'
mkdir -p /storage/torrent
rm -rf /storage/torrent/*.torrent
IMAGE=`cat /proc/cmdline | grep -o 'imgname=[^\ ]*' | grep -o '[^=]*$'`

cat /proc/cmdline | grep forcedownload
FORCE_DOWNLOAD=$?

[ $FORCE_DOWNLOAD -eq 0 ] && rm -rf /storage/casper/*

cd /storage/torrent

for i in filesystem.squashfs kernel.img initrd.img
do
    wget ${BASEURL}/${IMAGE}/$i.torrent
done
clear

gettorrent *.torrent || error "Failed to download torrent"
sync

IP=`ip addr show dev eth0 | grep -o 'inet\ [^\ /]*' | cut -d\  -f2`
SUFFIX=`echo $IP | cut -d. -f4`
HOSTNAME=`printf rig-%03d $SUFFIX`
TZ=Europe/Rome
cd /storage/casper
kexec kernel.img initrd.img "boot=casper hostname=${HOSTNAME} timezone=${TZ}" || error "kexec failed!"
